global.name = []
global.id = []
global.nickname = []
global.profile_image = []
global.email = []
global.birthday = []
global.login = []
global.realname = []
global.mobile = []
global.mobile_e164 = []
global.gender = []
global.birthyear = []
//푸시알림
global.pushindex = []